# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  # Lint
  - Rscript -e 'lintr::lint_package()'
  # Codecov
  - Rscript -e 'covr::codecov()'
  # Proselint
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # Goodpractice
  - Rscript -e 'goodpractice::gp()'

